# Generated by Django 4.2.23 on 2026-02-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_product_icon_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='Enter each feature on a new line'),
        ),
    ]
