# Generated by Django 4.2.23 on 2026-02-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_product_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD', max_digits=10, null=True),
        ),
    ]
